# Based on the guide from Ruddra
# https://ruddra.com/posts/hugo-deploy-static-page-using-github-actions/

name: Continuous Deployment
on: push

jobs:

  deploy:
    runs-on: ubuntu-18.04
    steps:

      # Checkout the github repo
      - name: Git checkout
        uses: actions/checkout@v2

      # Update the Academic theme module
      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      # Install hugo server
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      # Build the website
      - name: Build
        # add --minify tag if you  need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

      # Deploy the website to the user webpage
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CI_TOKEN }}
          external_repository: ktmeaton/ktmeaton.github.io
          publish_dir: ./public
          keep_files: true
          user_name: ktmeaton
          user_email: ktmeaton@gmail.com
          publish_branch: master
